FROM node:19.0.0 AS build
WORKDIR /my-app
COPY . .
RUN npm install
RUN npm run build
FROM nginx:1.18-alpine AS deploy-static
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /my-app/build/ .
ENTRYPOINT ["nginx", "-g", "daemon off;"]