version: '3.8'

services:

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "92:80"
    depends_on:
      - backend
      - frontend
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  frontend:
    restart: always
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/my-app/src
    ports:
      - "5173"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    networks:
      - main

  backend:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code
    ports:
      - "7776:8000"
    networks:
      - main
    env_file:
      - .env
    stdin_open: true
    tty: true

networks:
  main:
    driver: bridge